// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file card/v1alpha1/card_api.proto (package card.v1alpha1, syntax proto3)
/* eslint-disable */

import { CardService } from "./card_api_pb";

/**
 * Deal
 *
 * @generated from rpc card.v1alpha1.CardService.Deal
 */
export const deal = CardService.method.deal;

/**
 * Ping heartbeat
 *
 * @generated from rpc card.v1alpha1.CardService.Ping
 */
export const ping = CardService.method.ping;
