// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file card/v1alpha1/card_api.proto (package card.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Card } from "./card_pb";
import { file_card_v1alpha1_card } from "./card_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file card/v1alpha1/card_api.proto.
 */
export const file_card_v1alpha1_card_api: GenFile = /*@__PURE__*/
  fileDesc("ChxjYXJkL3YxYWxwaGExL2NhcmRfYXBpLnByb3RvEg1jYXJkLnYxYWxwaGExIg0KC0RlYWxSZXF1ZXN0IjEKDERlYWxSZXNwb25zZRIhCgRjYXJkGAEgASgLMhMuY2FyZC52MWFscGhhMS5DYXJkIjYKC1BpbmdSZXF1ZXN0EicKA25vdxgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiDgoMUGluZ1Jlc3BvbnNlMo8BCgtDYXJkU2VydmljZRI/CgREZWFsEhouY2FyZC52MWFscGhhMS5EZWFsUmVxdWVzdBobLmNhcmQudjFhbHBoYTEuRGVhbFJlc3BvbnNlEj8KBFBpbmcSGi5jYXJkLnYxYWxwaGExLlBpbmdSZXF1ZXN0GhsuY2FyZC52MWFscGhhMS5QaW5nUmVzcG9uc2VCNVozZ2l0aHViLmNvbS9vcGVucG9rZXItZGV2L2dlbmdvL2NhcmQvdjFhbHBoYTE7Y2FyZHBiYgZwcm90bzM", [file_card_v1alpha1_card, file_google_protobuf_timestamp]);

/**
 * DealRequest define request schema of Deal API
 *
 * @generated from message card.v1alpha1.DealRequest
 */
export type DealRequest = Message<"card.v1alpha1.DealRequest"> & {
};

/**
 * Describes the message card.v1alpha1.DealRequest.
 * Use `create(DealRequestSchema)` to create a new message.
 */
export const DealRequestSchema: GenMessage<DealRequest> = /*@__PURE__*/
  messageDesc(file_card_v1alpha1_card_api, 0);

/**
 * DealResponse define response schema of Deal API
 *
 * @generated from message card.v1alpha1.DealResponse
 */
export type DealResponse = Message<"card.v1alpha1.DealResponse"> & {
  /**
   * card entity of card
   *
   * @generated from field: card.v1alpha1.Card card = 1;
   */
  card?: Card;
};

/**
 * Describes the message card.v1alpha1.DealResponse.
 * Use `create(DealResponseSchema)` to create a new message.
 */
export const DealResponseSchema: GenMessage<DealResponse> = /*@__PURE__*/
  messageDesc(file_card_v1alpha1_card_api, 1);

/**
 * PingRequest define request schema of Ping API
 *
 * @generated from message card.v1alpha1.PingRequest
 */
export type PingRequest = Message<"card.v1alpha1.PingRequest"> & {
  /**
   * now is the timestamp when the request is sent
   *
   * @generated from field: google.protobuf.Timestamp now = 1;
   */
  now?: Timestamp;
};

/**
 * Describes the message card.v1alpha1.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_card_v1alpha1_card_api, 2);

/**
 * PingResponse define response schema of Ping API
 *
 * @generated from message card.v1alpha1.PingResponse
 */
export type PingResponse = Message<"card.v1alpha1.PingResponse"> & {
};

/**
 * Describes the message card.v1alpha1.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_card_v1alpha1_card_api, 3);

/**
 * CardService defins apis of CardService
 *
 * @generated from service card.v1alpha1.CardService
 */
export const CardService: GenService<{
  /**
   * Deal
   *
   * @generated from rpc card.v1alpha1.CardService.Deal
   */
  deal: {
    methodKind: "unary";
    input: typeof DealRequestSchema;
    output: typeof DealResponseSchema;
  },
  /**
   * Ping heartbeat
   *
   * @generated from rpc card.v1alpha1.CardService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_card_v1alpha1_card_api, 0);

