/**
 * @fileoverview gRPC-Web generated client stub for card.v1alpha1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v0.0.0
// source: card/v1alpha1/card_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.card.v1alpha1.CardServiceClient');
goog.provide('proto.card.v1alpha1.CardServicePromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.card.v1alpha1.DealRequest');
goog.require('proto.card.v1alpha1.DealResponse');
goog.require('proto.card.v1alpha1.PingRequest');
goog.require('proto.card.v1alpha1.PingResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.card.v1alpha1.CardServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.card.v1alpha1.CardServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.card.v1alpha1.DealRequest,
 *   !proto.card.v1alpha1.DealResponse>}
 */
const methodDescriptor_CardService_Deal = new grpc.web.MethodDescriptor(
  '/card.v1alpha1.CardService/Deal',
  grpc.web.MethodType.UNARY,
  proto.card.v1alpha1.DealRequest,
  proto.card.v1alpha1.DealResponse,
  /**
   * @param {!proto.card.v1alpha1.DealRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.card.v1alpha1.DealResponse.deserializeBinary
);


/**
 * @param {!proto.card.v1alpha1.DealRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.card.v1alpha1.DealResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.card.v1alpha1.DealResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.card.v1alpha1.CardServiceClient.prototype.deal =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/card.v1alpha1.CardService/Deal',
      request,
      metadata || {},
      methodDescriptor_CardService_Deal,
      callback);
};


/**
 * @param {!proto.card.v1alpha1.DealRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.card.v1alpha1.DealResponse>}
 *     Promise that resolves to the response
 */
proto.card.v1alpha1.CardServicePromiseClient.prototype.deal =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/card.v1alpha1.CardService/Deal',
      request,
      metadata || {},
      methodDescriptor_CardService_Deal);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.card.v1alpha1.PingRequest,
 *   !proto.card.v1alpha1.PingResponse>}
 */
const methodDescriptor_CardService_Ping = new grpc.web.MethodDescriptor(
  '/card.v1alpha1.CardService/Ping',
  grpc.web.MethodType.UNARY,
  proto.card.v1alpha1.PingRequest,
  proto.card.v1alpha1.PingResponse,
  /**
   * @param {!proto.card.v1alpha1.PingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.card.v1alpha1.PingResponse.deserializeBinary
);


/**
 * @param {!proto.card.v1alpha1.PingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.card.v1alpha1.PingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.card.v1alpha1.PingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.card.v1alpha1.CardServiceClient.prototype.ping =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/card.v1alpha1.CardService/Ping',
      request,
      metadata || {},
      methodDescriptor_CardService_Ping,
      callback);
};


/**
 * @param {!proto.card.v1alpha1.PingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.card.v1alpha1.PingResponse>}
 *     Promise that resolves to the response
 */
proto.card.v1alpha1.CardServicePromiseClient.prototype.ping =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/card.v1alpha1.CardService/Ping',
      request,
      metadata || {},
      methodDescriptor_CardService_Ping);
};


}); // goog.scope

