// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file card/v1alpha1/card.proto (package card.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file card/v1alpha1/card.proto.
 */
export const file_card_v1alpha1_card: GenFile = /*@__PURE__*/
  fileDesc("ChhjYXJkL3YxYWxwaGExL2NhcmQucHJvdG8SDWNhcmQudjFhbHBoYTEiTAoEQ2FyZBIhCgRzdWl0GAEgASgOMhMuY2FyZC52MWFscGhhMS5TdWl0EiEKBHJhbmsYAiABKA4yEy5jYXJkLnYxYWxwaGExLlJhbmsqiQIKBFJhbmsSFAoQUkFOS19VTlNQRUNJRklFRBAAEgwKCFJBTktfQUNFEAESDAoIUkFOS19UV08QAhIOCgpSQU5LX1RIUkVFEAMSDQoJUkFOS19GT1VSEAQSDQoJUkFOS19GSVZFEAUSDAoIUkFOS19TSVgQBhIOCgpSQU5LX1NFVkVOEAcSDgoKUkFOS19FSUdIVBAIEg0KCVJBTktfTklORRAJEgwKCFJBTktfVEVOEAoSDQoJUkFOS19KQUNLEAsSDgoKUkFOS19RVUVFThAMEg0KCVJBTktfS0lORxANEhQKEFJBTktfU01BTExfSk9LRVIQDhISCg5SQU5LX0JJR19KT0tFUhAPKmEKBFN1aXQSFAoQU1VJVF9VTlNQRUNJRklFRBAAEg8KC1NVSVRfSEVBUlRTEAESDwoLU1VJVF9TUEFERVMQAhIRCg1TVUlUX0RJQU1PTkRTEAMSDgoKU1VJVF9DTFVCUxAEKncKBVJvdW5kEhUKEVJPVU5EX1VOU1BFQ0lGSUVEEAASEgoOUk9VTkRfUFJFX0ZMT1AQARIOCgpST1VORF9GTE9QEAISDgoKUk9VTkRfVFVSThADEg8KC1JPVU5EX1JJVkVSEAQSEgoOUk9VTkRfU0hPV0RPV04QBSrbAgoMSGFuZENhdGVnb3J5Eh0KGUhBTkRfQ0FURUdPUllfVU5TUEVDSUZJRUQQABIbChdIQU5EX0NBVEVHT1JZX0hJR0hfQ0FSRBABEhoKFkhBTkRfQ0FURUdPUllfT05FX1BBSVIQAhIaChZIQU5EX0NBVEVHT1JZX1RXT19QQUlSEAMSIQodSEFORF9DQVRFR09SWV9USFJFRV9PRl9BX0tJTkQQBBIaChZIQU5EX0NBVEVHT1JZX1NUUkFJR0hUEAUSFwoTSEFORF9DQVRFR09SWV9GTFVTSBAGEhwKGEhBTkRfQ0FURUdPUllfRlVMTF9IT1VTRRAHEiAKHEhBTkRfQ0FURUdPUllfRk9VUl9PRl9BX0tJTkQQCBIgChxIQU5EX0NBVEVHT1JZX1NUUkFJR0hUX0ZMVVNIEAkSHQoZSEFORF9DQVRFR09SWV9ST1lBTF9GTFVTSBAKQjVaM2dpdGh1Yi5jb20vb3BlbnBva2VyLWRldi9nZW5nby9jYXJkL3YxYWxwaGExO2NhcmRwYmIGcHJvdG8z");

/**
 * Card represents a playing card.
 *
 * @generated from message card.v1alpha1.Card
 */
export type Card = Message<"card.v1alpha1.Card"> & {
  /**
   * suit of the card.
   *
   * @generated from field: card.v1alpha1.Suit suit = 1;
   */
  suit: Suit;

  /**
   * rank of the card.
   *
   * @generated from field: card.v1alpha1.Rank rank = 2;
   */
  rank: Rank;
};

/**
 * Describes the message card.v1alpha1.Card.
 * Use `create(CardSchema)` to create a new message.
 */
export const CardSchema: GenMessage<Card> = /*@__PURE__*/
  messageDesc(file_card_v1alpha1_card, 0);

/**
 * Rank represents the rank of a playing card.
 *
 * @generated from enum card.v1alpha1.Rank
 */
export enum Rank {
  /**
   * RANK_UNSPECIFIED represents an unspecified rank.
   *
   * @generated from enum value: RANK_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * RANK_ACE represents an Ace.
   *
   * @generated from enum value: RANK_ACE = 1;
   */
  ACE = 1,

  /**
   * RANK_TWO represents a 2.
   *
   * @generated from enum value: RANK_TWO = 2;
   */
  TWO = 2,

  /**
   * RANK_THREE represents a 3.
   *
   * @generated from enum value: RANK_THREE = 3;
   */
  THREE = 3,

  /**
   * RANK_FOUR represents a 4.
   *
   * @generated from enum value: RANK_FOUR = 4;
   */
  FOUR = 4,

  /**
   * RANK_FIVE represents a 5.
   *
   * @generated from enum value: RANK_FIVE = 5;
   */
  FIVE = 5,

  /**
   * RANK_SIX represents a 6.
   *
   * @generated from enum value: RANK_SIX = 6;
   */
  SIX = 6,

  /**
   * RANK_SEVEN represents a 7.
   *
   * @generated from enum value: RANK_SEVEN = 7;
   */
  SEVEN = 7,

  /**
   * RANK_EIGHT represents an 8.
   *
   * @generated from enum value: RANK_EIGHT = 8;
   */
  EIGHT = 8,

  /**
   * RANK_NINE represents a 9.
   *
   * @generated from enum value: RANK_NINE = 9;
   */
  NINE = 9,

  /**
   * RANK_TEN represents a 10.
   *
   * @generated from enum value: RANK_TEN = 10;
   */
  TEN = 10,

  /**
   * RANK_JACK represents a Jack.
   *
   * @generated from enum value: RANK_JACK = 11;
   */
  JACK = 11,

  /**
   * RANK_QUEEN represents a Queen.
   *
   * @generated from enum value: RANK_QUEEN = 12;
   */
  QUEEN = 12,

  /**
   * RANK_KING represents a King.
   *
   * @generated from enum value: RANK_KING = 13;
   */
  KING = 13,

  /**
   * RANK_SMALL_JOKER represents a Small Joker.
   *
   * @generated from enum value: RANK_SMALL_JOKER = 14;
   */
  SMALL_JOKER = 14,

  /**
   * RANK_BIG_JOKER represents a Big Joker.
   *
   * @generated from enum value: RANK_BIG_JOKER = 15;
   */
  BIG_JOKER = 15,
}

/**
 * Describes the enum card.v1alpha1.Rank.
 */
export const RankSchema: GenEnum<Rank> = /*@__PURE__*/
  enumDesc(file_card_v1alpha1_card, 0);

/**
 * Suit represents the suit of a playing card.
 *
 * @generated from enum card.v1alpha1.Suit
 */
export enum Suit {
  /**
   * SUIT_UNSPECIFIED represents an unspecified suit.
   *
   * @generated from enum value: SUIT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * SUIT_HEARTS represents the hearts suit.
   *
   * @generated from enum value: SUIT_HEARTS = 1;
   */
  HEARTS = 1,

  /**
   * SUIT_SPADES represents the spades suit.
   *
   * @generated from enum value: SUIT_SPADES = 2;
   */
  SPADES = 2,

  /**
   * SUIT_DIAMONDS represents the diamonds suit.
   *
   * @generated from enum value: SUIT_DIAMONDS = 3;
   */
  DIAMONDS = 3,

  /**
   * SUIT_CLUBS represents the clubs suit.
   *
   * @generated from enum value: SUIT_CLUBS = 4;
   */
  CLUBS = 4,
}

/**
 * Describes the enum card.v1alpha1.Suit.
 */
export const SuitSchema: GenEnum<Suit> = /*@__PURE__*/
  enumDesc(file_card_v1alpha1_card, 1);

/**
 * Round represents the round of a poker game.
 *
 * @generated from enum card.v1alpha1.Round
 */
export enum Round {
  /**
   * ROUND_UNSPECIFIED represents an unspecified round.
   *
   * @generated from enum value: ROUND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * ROUND_PRE_FLOP represents the pre-flop round.
   *
   * @generated from enum value: ROUND_PRE_FLOP = 1;
   */
  PRE_FLOP = 1,

  /**
   * ROUND_FLOP represents the flop round.
   *
   * @generated from enum value: ROUND_FLOP = 2;
   */
  FLOP = 2,

  /**
   * ROUND_TURN represents the turn round.
   *
   * @generated from enum value: ROUND_TURN = 3;
   */
  TURN = 3,

  /**
   * ROUND_RIVER represents the river round.
   *
   * @generated from enum value: ROUND_RIVER = 4;
   */
  RIVER = 4,

  /**
   * ROUND_SHOWDOWN represents the showdown round.
   *
   * @generated from enum value: ROUND_SHOWDOWN = 5;
   */
  SHOWDOWN = 5,
}

/**
 * Describes the enum card.v1alpha1.Round.
 */
export const RoundSchema: GenEnum<Round> = /*@__PURE__*/
  enumDesc(file_card_v1alpha1_card, 2);

/**
 * HandCategory represents the category of a poker hand.
 *
 * @generated from enum card.v1alpha1.HandCategory
 */
export enum HandCategory {
  /**
   * HAND_CATEGORY_UNSPECIFIED represents an unspecified hand category.
   *
   * @generated from enum value: HAND_CATEGORY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * HAND_CATEGORY_HIGH_CARD represents a high card hand.
   *
   * @generated from enum value: HAND_CATEGORY_HIGH_CARD = 1;
   */
  HIGH_CARD = 1,

  /**
   * HAND_CATEGORY_ONE_PAIR represents a one pair hand.
   *
   * @generated from enum value: HAND_CATEGORY_ONE_PAIR = 2;
   */
  ONE_PAIR = 2,

  /**
   * HAND_CATEGORY_TWO_PAIR represents a two pair hand.
   *
   * @generated from enum value: HAND_CATEGORY_TWO_PAIR = 3;
   */
  TWO_PAIR = 3,

  /**
   * HAND_CATEGORY_THREE_OF_A_KIND represents a three of a kind hand.
   *
   * @generated from enum value: HAND_CATEGORY_THREE_OF_A_KIND = 4;
   */
  THREE_OF_A_KIND = 4,

  /**
   * HAND_CATEGORY_STRAIGHT represents a straight hand.
   *
   * @generated from enum value: HAND_CATEGORY_STRAIGHT = 5;
   */
  STRAIGHT = 5,

  /**
   * HAND_CATEGORY_FLUSH represents a flush hand.
   *
   * @generated from enum value: HAND_CATEGORY_FLUSH = 6;
   */
  FLUSH = 6,

  /**
   * HAND_CATEGORY_FULL_HOUSE represents a full house hand.
   *
   * @generated from enum value: HAND_CATEGORY_FULL_HOUSE = 7;
   */
  FULL_HOUSE = 7,

  /**
   * HAND_CATEGORY_FOUR_OF_A_KIND represents a four of a kind hand.
   *
   * @generated from enum value: HAND_CATEGORY_FOUR_OF_A_KIND = 8;
   */
  FOUR_OF_A_KIND = 8,

  /**
   * HAND_CATEGORY_STRAIGHT_FLUSH represents a straight flush hand.
   *
   * @generated from enum value: HAND_CATEGORY_STRAIGHT_FLUSH = 9;
   */
  STRAIGHT_FLUSH = 9,

  /**
   * HAND_CATEGORY_ROYAL_FLUSH represents a royal flush hand.
   *
   * @generated from enum value: HAND_CATEGORY_ROYAL_FLUSH = 10;
   */
  ROYAL_FLUSH = 10,
}

/**
 * Describes the enum card.v1alpha1.HandCategory.
 */
export const HandCategorySchema: GenEnum<HandCategory> = /*@__PURE__*/
  enumDesc(file_card_v1alpha1_card, 3);

