// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file game/v1alpha1/game.proto (package game.v1alpha1, syntax proto3)
/* eslint-disable */

import { GameService } from "./game_pb";

/**
 * CreateGame creates a new game room.
 *
 * @generated from rpc game.v1alpha1.GameService.CreateGame
 */
export const createGame = GameService.method.createGame;

/**
 * JoinGame joins an existing game room.
 *
 * @generated from rpc game.v1alpha1.GameService.JoinGame
 */
export const joinGame = GameService.method.joinGame;

/**
 * StartGame starts the game (usually restricted to the host).
 *
 * @generated from rpc game.v1alpha1.GameService.StartGame
 */
export const startGame = GameService.method.startGame;

/**
 * PlayAction performs a player action (Fold, Check, Call, Raise).
 *
 * @generated from rpc game.v1alpha1.GameService.PlayAction
 */
export const playAction = GameService.method.playAction;

/**
 * GetGameState retrieves the current game state (used for polling or reconnection).
 *
 * @generated from rpc game.v1alpha1.GameService.GetGameState
 */
export const getGameState = GameService.method.getGameState;

/**
 * KickPlayer allows the host to remove a player (or bot) from the game.
 * This is only allowed when the game is in "Waiting" or "Finished" status.
 *
 * @generated from rpc game.v1alpha1.GameService.KickPlayer
 */
export const kickPlayer = GameService.method.kickPlayer;
