/**
 * @fileoverview gRPC-Web generated client stub for game.v1alpha1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v0.0.0
// source: game/v1alpha1/game.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.game.v1alpha1.GameServiceClient');
goog.provide('proto.game.v1alpha1.GameServicePromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.game.v1alpha1.CreateGameRequest');
goog.require('proto.game.v1alpha1.CreateGameResponse');
goog.require('proto.game.v1alpha1.GetGameStateRequest');
goog.require('proto.game.v1alpha1.GetGameStateResponse');
goog.require('proto.game.v1alpha1.JoinGameRequest');
goog.require('proto.game.v1alpha1.JoinGameResponse');
goog.require('proto.game.v1alpha1.KickPlayerRequest');
goog.require('proto.game.v1alpha1.KickPlayerResponse');
goog.require('proto.game.v1alpha1.PlayActionRequest');
goog.require('proto.game.v1alpha1.PlayActionResponse');
goog.require('proto.game.v1alpha1.StartGameRequest');
goog.require('proto.game.v1alpha1.StartGameResponse');
goog.require('proto.game.v1alpha1.WatchGameRequest');
goog.require('proto.game.v1alpha1.WatchGameResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.v1alpha1.GameServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.v1alpha1.GameServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.v1alpha1.CreateGameRequest,
 *   !proto.game.v1alpha1.CreateGameResponse>}
 */
const methodDescriptor_GameService_CreateGame = new grpc.web.MethodDescriptor(
  '/game.v1alpha1.GameService/CreateGame',
  grpc.web.MethodType.UNARY,
  proto.game.v1alpha1.CreateGameRequest,
  proto.game.v1alpha1.CreateGameResponse,
  /**
   * @param {!proto.game.v1alpha1.CreateGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.v1alpha1.CreateGameResponse.deserializeBinary
);


/**
 * @param {!proto.game.v1alpha1.CreateGameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.v1alpha1.CreateGameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.v1alpha1.CreateGameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.v1alpha1.GameServiceClient.prototype.createGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.v1alpha1.GameService/CreateGame',
      request,
      metadata || {},
      methodDescriptor_GameService_CreateGame,
      callback);
};


/**
 * @param {!proto.game.v1alpha1.CreateGameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.v1alpha1.CreateGameResponse>}
 *     Promise that resolves to the response
 */
proto.game.v1alpha1.GameServicePromiseClient.prototype.createGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.v1alpha1.GameService/CreateGame',
      request,
      metadata || {},
      methodDescriptor_GameService_CreateGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.v1alpha1.JoinGameRequest,
 *   !proto.game.v1alpha1.JoinGameResponse>}
 */
const methodDescriptor_GameService_JoinGame = new grpc.web.MethodDescriptor(
  '/game.v1alpha1.GameService/JoinGame',
  grpc.web.MethodType.UNARY,
  proto.game.v1alpha1.JoinGameRequest,
  proto.game.v1alpha1.JoinGameResponse,
  /**
   * @param {!proto.game.v1alpha1.JoinGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.v1alpha1.JoinGameResponse.deserializeBinary
);


/**
 * @param {!proto.game.v1alpha1.JoinGameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.v1alpha1.JoinGameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.v1alpha1.JoinGameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.v1alpha1.GameServiceClient.prototype.joinGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.v1alpha1.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame,
      callback);
};


/**
 * @param {!proto.game.v1alpha1.JoinGameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.v1alpha1.JoinGameResponse>}
 *     Promise that resolves to the response
 */
proto.game.v1alpha1.GameServicePromiseClient.prototype.joinGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.v1alpha1.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.v1alpha1.StartGameRequest,
 *   !proto.game.v1alpha1.StartGameResponse>}
 */
const methodDescriptor_GameService_StartGame = new grpc.web.MethodDescriptor(
  '/game.v1alpha1.GameService/StartGame',
  grpc.web.MethodType.UNARY,
  proto.game.v1alpha1.StartGameRequest,
  proto.game.v1alpha1.StartGameResponse,
  /**
   * @param {!proto.game.v1alpha1.StartGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.v1alpha1.StartGameResponse.deserializeBinary
);


/**
 * @param {!proto.game.v1alpha1.StartGameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.v1alpha1.StartGameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.v1alpha1.StartGameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.v1alpha1.GameServiceClient.prototype.startGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.v1alpha1.GameService/StartGame',
      request,
      metadata || {},
      methodDescriptor_GameService_StartGame,
      callback);
};


/**
 * @param {!proto.game.v1alpha1.StartGameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.v1alpha1.StartGameResponse>}
 *     Promise that resolves to the response
 */
proto.game.v1alpha1.GameServicePromiseClient.prototype.startGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.v1alpha1.GameService/StartGame',
      request,
      metadata || {},
      methodDescriptor_GameService_StartGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.v1alpha1.PlayActionRequest,
 *   !proto.game.v1alpha1.PlayActionResponse>}
 */
const methodDescriptor_GameService_PlayAction = new grpc.web.MethodDescriptor(
  '/game.v1alpha1.GameService/PlayAction',
  grpc.web.MethodType.UNARY,
  proto.game.v1alpha1.PlayActionRequest,
  proto.game.v1alpha1.PlayActionResponse,
  /**
   * @param {!proto.game.v1alpha1.PlayActionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.v1alpha1.PlayActionResponse.deserializeBinary
);


/**
 * @param {!proto.game.v1alpha1.PlayActionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.v1alpha1.PlayActionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.v1alpha1.PlayActionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.v1alpha1.GameServiceClient.prototype.playAction =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.v1alpha1.GameService/PlayAction',
      request,
      metadata || {},
      methodDescriptor_GameService_PlayAction,
      callback);
};


/**
 * @param {!proto.game.v1alpha1.PlayActionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.v1alpha1.PlayActionResponse>}
 *     Promise that resolves to the response
 */
proto.game.v1alpha1.GameServicePromiseClient.prototype.playAction =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.v1alpha1.GameService/PlayAction',
      request,
      metadata || {},
      methodDescriptor_GameService_PlayAction);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.v1alpha1.GetGameStateRequest,
 *   !proto.game.v1alpha1.GetGameStateResponse>}
 */
const methodDescriptor_GameService_GetGameState = new grpc.web.MethodDescriptor(
  '/game.v1alpha1.GameService/GetGameState',
  grpc.web.MethodType.UNARY,
  proto.game.v1alpha1.GetGameStateRequest,
  proto.game.v1alpha1.GetGameStateResponse,
  /**
   * @param {!proto.game.v1alpha1.GetGameStateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.v1alpha1.GetGameStateResponse.deserializeBinary
);


/**
 * @param {!proto.game.v1alpha1.GetGameStateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.v1alpha1.GetGameStateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.v1alpha1.GetGameStateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.v1alpha1.GameServiceClient.prototype.getGameState =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.v1alpha1.GameService/GetGameState',
      request,
      metadata || {},
      methodDescriptor_GameService_GetGameState,
      callback);
};


/**
 * @param {!proto.game.v1alpha1.GetGameStateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.v1alpha1.GetGameStateResponse>}
 *     Promise that resolves to the response
 */
proto.game.v1alpha1.GameServicePromiseClient.prototype.getGameState =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.v1alpha1.GameService/GetGameState',
      request,
      metadata || {},
      methodDescriptor_GameService_GetGameState);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.v1alpha1.WatchGameRequest,
 *   !proto.game.v1alpha1.WatchGameResponse>}
 */
const methodDescriptor_GameService_WatchGame = new grpc.web.MethodDescriptor(
  '/game.v1alpha1.GameService/WatchGame',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.game.v1alpha1.WatchGameRequest,
  proto.game.v1alpha1.WatchGameResponse,
  /**
   * @param {!proto.game.v1alpha1.WatchGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.v1alpha1.WatchGameResponse.deserializeBinary
);


/**
 * @param {!proto.game.v1alpha1.WatchGameRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.v1alpha1.WatchGameResponse>}
 *     The XHR Node Readable Stream
 */
proto.game.v1alpha1.GameServiceClient.prototype.watchGame =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.v1alpha1.GameService/WatchGame',
      request,
      metadata || {},
      methodDescriptor_GameService_WatchGame);
};


/**
 * @param {!proto.game.v1alpha1.WatchGameRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.v1alpha1.WatchGameResponse>}
 *     The XHR Node Readable Stream
 */
proto.game.v1alpha1.GameServicePromiseClient.prototype.watchGame =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.v1alpha1.GameService/WatchGame',
      request,
      metadata || {},
      methodDescriptor_GameService_WatchGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.v1alpha1.KickPlayerRequest,
 *   !proto.game.v1alpha1.KickPlayerResponse>}
 */
const methodDescriptor_GameService_KickPlayer = new grpc.web.MethodDescriptor(
  '/game.v1alpha1.GameService/KickPlayer',
  grpc.web.MethodType.UNARY,
  proto.game.v1alpha1.KickPlayerRequest,
  proto.game.v1alpha1.KickPlayerResponse,
  /**
   * @param {!proto.game.v1alpha1.KickPlayerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.v1alpha1.KickPlayerResponse.deserializeBinary
);


/**
 * @param {!proto.game.v1alpha1.KickPlayerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.v1alpha1.KickPlayerResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.v1alpha1.KickPlayerResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.v1alpha1.GameServiceClient.prototype.kickPlayer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.v1alpha1.GameService/KickPlayer',
      request,
      metadata || {},
      methodDescriptor_GameService_KickPlayer,
      callback);
};


/**
 * @param {!proto.game.v1alpha1.KickPlayerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.v1alpha1.KickPlayerResponse>}
 *     Promise that resolves to the response
 */
proto.game.v1alpha1.GameServicePromiseClient.prototype.kickPlayer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.v1alpha1.GameService/KickPlayer',
      request,
      metadata || {},
      methodDescriptor_GameService_KickPlayer);
};


}); // goog.scope

